### ISSUE TITLE
"Turn off any sources using Mon2Cam before starting script"

### ISSUE THREAD

**Issue by TogarUshindi** [ShayBox/Mon2Cam#10]
I haven't had the opportunity to use Mon2Cam since my last open issue, but now that I tried, after selecting my monitor, it comes up with this error, then dumps out to command prompt:

"Turn off any sources using Mon2Cam before starting script"

afaik I don't have any sources using Mon2Cam running. In fact, just to confirm, I restarted my system, and it's still happening. How can I check to see if anything is running that might be conflicting? Dependencies, etc?

**Comment by TogarUshindi** [comment]
I suddenly realized, if there was any specific thing I should add that could be relevant to this is that I had a graphic card change since three weeks ago. I had an old GeForce9, but now am using a hand-me-down GTX 1070. The driver I am using is the recommended one:

`driver   : nvidia-driver-440 - third-party free recommended`

**Comment by TogarUshindi** [comment]
I just rolled back to the proprietary `nvidia-driver-435` and no change in behavior.

**Comment by TogarUshindi** [comment]
Just tried unplugging one of the monitors to see if it was the HDMI-to-DVI adapter causing the issue, and it still shows up with the error.

**Comment by ShayBox** [comment]
Change your webcam source in discord settings, it's still using the webcam even when not in a call

**Comment by TogarUshindi** [comment]
I don't have a webcam.

![image](https://user-images.githubusercontent.com/54905590/68717995-f4c67b80-055c-11ea-9a43-189d5e497758.png)

(In fact, Mon2Cam is giving me that message even when Discord isn't running.)

**Comment by TogarUshindi** [comment]
Figured it out! Had to recompile v4l2loopback. Might be because the video hardware changed? Or some other reason. Not sure, don't care, it's working!

**Comment by ShayBox** [comment]
That's weird
