### ISSUE TITLE
Unable to unload v4l2loopback, Close any programs using virtual video devices and try again

### ISSUE THREAD

**Issue by teunissenstefan** [ShayBox/Mon2Cam#12]
When trying to start Mon2Cam I basically get this message: `Unable to unload v4l2loopback, Close any programs using virtual video devices and try again`.

I've tried manually unloading v4l2loopback, and reinstalling v4l2loopback but it still doesn't work.

I'm on Manjaro with kernel 5.4.23-1-MANJARO.

**Comment by ShayBox** [comment]
It just means any error happened when trying to unload v4l2loopback, try `sudo modprobe -r v4l2loopback` and see if that works, if something like discord is using any webcam, even just having the settings page open on the video page uses the webcam.

**Comment by teunissenstefan** [comment]
I had recently done a system upgrade and forgot to reboot. A reboot fixed it. I'm sorry, I am an idiot. Thanks for the help though 😄

**Comment by ShayBox** [comment]
No problem, things like that are confusing with no real error

**Comment by AkumuKernel** [comment]
Hi, hi, i have same problem, but, i tried to use sudo sudo 
`modprobe -r v4l2loopback`
and:
`modprobe: FATAL: Module v4l2loopback not found.`
I have v4l2loopback installed
I'm on Linux archiso 5.6.10-arch1-1

**Comment by lefuturiste** [comment]
Same error as @RioluTres

**Comment by AkumuKernel** [comment]
> Same error as @RioluTres
@lefuturiste 
Hi, hi, I solve the problem installing v4l2loopback-git, try to install this v4l2loopback :)

**Comment by ShayBox** [comment]
If you're getting `Module v4l2loopback not found` you have to install v4l2loopback

**Comment by AkumuKernel** [comment]
@ShayBox i solve this problem, but now i active mon2cam but can't appears the image when i start mon2cam

**Comment by lefuturiste** [comment]
@ShayBox But, but, `v4l2loopback` is installed, see here: https://gist.github.com/lefuturiste/ce470a25b2c61dfd5db3b502dd8b1825

![image](https://user-images.githubusercontent.com/20988163/81497009-fd093480-92bb-11ea-89a4-3d93f240f4ab.png)

**Comment by ShayBox** [comment]
You also have your kernel headers installed and rebooted?

**Comment by lefuturiste** [comment]
Yes I have the `core/linux-headers` arch package installed and rebooted many times
