### ISSUE TITLE
No Error message if Error Code

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [ShayBox/Mon2Cam#13]
Hey,
Using Fedora 32 here.

`command -v <command>` gives a non zero return code if the command couldn´t be found.
You set with `set -o errexit` to exit the script on non zero return codes, why?

In my case I hadn't installed ffmpeg and the script exited without any error message. 
I would recommend to remove the `set -o errexit`  policy. 

![Screenshot_20200521_200542](https://user-images.githubusercontent.com/30468956/82590755-89f69c80-9b9e-11ea-8b0c-e46b6e303221.png)

kind regards.

**Comment by ShayBox** [comment]
Good catch, I added that after to make it more strict

**Comment by Lukas-Heiligenbrunner** [comment]
Thanks! 
works great for me now.
