### ISSUE TITLE
ffmpeg errors are ignored and not shown

### ISSUE THREAD

**Issue by Niko-sk2x** [ShayBox/Mon2Cam#14]
Using gentoo, I didn't have `v4l` use flag enabled on ffmpeg so it was erroring with this:

```
[x11grab @ 0x562173462bc0] Cannot open display VGA1+0,0, error 5.
VGA1+0,0: Input/output error
```

but Mon2Cam didn't show any error

**Comment by botiapa** [comment]
Currently the output of ffmpeg is piped into `/dev/null`. Instead the `stderr` should be put into a variable, and at the end of the script it should check if the variable is null or not. If not, then it should echo the error.

@ShayBox I could write this feature later, unless you want to work on it.

**Comment by ShayBox** [comment]
I thought I had it log if verbose was enabled, but I guess not, I won't be home for a while so work on it if you want

**Comment by ShayBox** [comment]
Added a verbose option to switch redirection output of ffmpeg
https://github.com/ShayBox/Mon2Cam/commit/e842cf76408917870a8c0369cfe3ddf0994c8087
