### ISSUE TITLE
Unable to unload v4l2loopback, Close any programs using virtual video devices and try again

### ISSUE THREAD

**Issue by hasantezcan** [ShayBox/Mon2Cam#15]
I get every time when I tried to execute Mon2Cam command I get `Unable to unload v4l2loopback, Close any programs using virtual video devices and try again` this error message! 

**Note:** I setup the program with Aur helper and my OS is Manjaro with Kernel 5.4.40-1
And checked this issue also https://github.com/ShayBox/Mon2Cam/issues/12

![image](https://user-images.githubusercontent.com/32804505/83204755-47603180-a155-11ea-896e-4825ed141be9.png)

**Comment by ShayBox** [comment]
You don't have the v4l2 loop back module loaded, make sure you have your kernels modules installed, regenerated your initram, and rebooted

**Comment by PegasisForever** [comment]
I fixed this by:
```
sudo pacman-mirrors -f 5 && sudo pacman -Syyu     #update mirror and system
sudo pacman -S $(pacman -Qsq "^linux" | grep "^linux[0-9]*[-rt]*$" | awk '{print $1"-headers"}' ORS=' ')     #install kernel headers
```
Reboot, then:
```
sudo pacman -S v4l2loopback-dkms     #reinstall v4l2loopback
sudo modprobe v4l2loopback     #load v4l2loopback
```
