### ISSUE TITLE
Uninstall Mon2Cam

### ISSUE THREAD

**Issue by danrleypereira** [ShayBox/Mon2Cam#19]
How can I remove Mon2Cam of my linux OS?

**Comment by ShayBox** [comment]
Delete the file you downloaded, it's a single script

**Comment by botiapa** [comment]
@danrleywillyan How did you install it? If you used the arch linux AUR, then you should delete it that way.

**Comment by botiapa** [comment]
@danrleywillyan Is the issue solved? Can it be closed?

No reply after a week. Closing the issue. If you still need help, feel free to reopen.
