### ISSUE TITLE
Fix audio streaming

### ISSUE THREAD

**Issue by botiapa** [ShayBox/Mon2Cam#25]
Currently if you stream you either can't hear the application(s) you're streaming, or if you use ffplay, then you can hear **yourself**.

This is obviously not ideal and kind of defeats the purpose. I'm not sure if this issue is solvable.

@ShayBox Any ideas maybe for a fix for this?

**Comment by ShayBox** [comment]
You may possibly be able to create a monitor and loop it back into the main output, but pulse stuff is quite complex

**Comment by botiapa** [comment]
Essentially if you use ffplay to play the monitor of the VirtualSink, then it does what you said. But the virtual sink has your microphone attached, therefore you hear yourself. I hope you understand what I mean.

**Comment by ShayBox** [comment]
Hmm, is it possible to create a virtual sink of the application, loop that back to the system output, then create another virtual sink of the first sink + microphone for discord?

**Comment by botiapa** [comment]
Yes this would be possible (I think). I'll try to implement it when I have time. The disadvantages I can see right away are possibly high cpu usage and audio delay. We'll see.

**Comment by ShayBox** [comment]
Yeah, all around shitty situation, but for a built-in pulseaudio solution it will have to do, if people really want they can install and setup jack sinks/loops on their own system for latency and processing free setups :/

**Comment by botiapa** [comment]
Check #28

**Comment by botiapa** [comment]
This is fixed in the wayland update.
