### ISSUE TITLE
Adding optional dependencies

### ISSUE THREAD

**Issue by botiapa** [ShayBox/Mon2Cam#27]
If the wayland PR gets merged, then I think it would be a good idea to add `xisxwayland`, `wayland`, `wlr-randr` and `wf-recorder` as an optional dependency in the AUR package.

**Comment by ShayBox** [comment]
Thanks for reminding me, I'll do that when it gets merged

**Comment by botiapa** [comment]
This is closable right?

**Comment by ShayBox** [comment]
yep
