### ISSUE TITLE
Clean up output

### ISSUE THREAD

**Issue by botiapa** [ShayBox/Mon2Cam#29]
The output of the program is getting quite big, and it's not very well organized either. What do you think about adding basic coloring for the program, so it's more easily readable? If you think it's not a problem, then this is closable.

**Comment by ShayBox** [comment]
Color output would be great, btw my discord is Shay#2000 and https://discord.shaybox.com/ so we can talk without having to use github issues all the time :+1:

**Comment by botiapa** [comment]
This is fixed in the wayland update.
