### ISSUE TITLE
Won't display anything if the display size is above 1080p

### ISSUE THREAD

**Issue by AkaiiKitsune** [ShayBox/Mon2Cam#30]
This won't work if you're trying to run the app with no arguments on a 1440p screen, works when you use `Mon2Cam -m 0 -r 1920:1080`  though !

Maybe it should automatically fallback to 1920*1080 by default if the selected screen resolution is above 1080p ?

**Comment by ShayBox** [comment]
What's your native resolution, I've only had issues with discord if it wasn't 16:9 aspect ratio

**Comment by AkaiiKitsune** [comment]
That screen is 2560x1440, i run a triple screen setup as follows : 
` 0: +*HDMI-0 2560/597x1440/336+1920+0  HDMI-0
 1: +DVI-D-0 1920/531x1080/299+4480+579  DVI-D-0
 2: +DP-3 1920/531x1080/299+0+579  DP-3
`
It works out of the box for screens 1 and 2, but screen 0, the 2k one, needs the resolution parameters to be below 1920*1080 otherwise nothing shows up

**Comment by botiapa** [comment]
If I had to guess it's probably because discord only supports a list of resolutions. And probably there's a standard for cameras that define what resolutions are supported. But this is only a guess. If someone could test this with a 4k monitor that'd be great.

**Comment by AkaiiKitsune** [comment]
Probably, i'll try to see if i can ask a friend to try it out on his monitor

**Comment by botiapa** [comment]
Cool thanks. I think it should work with a 4k monitor , because there are surely 4k cams around. The big question is if discord supports it. (You might need nitro, or they might downscale it, I have no idea)

**Comment by kattjevfel** [comment]
I literally added the `-r` option for this exact reason, I too have a 2560x1440 screen and setting it to 1080p solves it.

**Comment by botiapa** [comment]
@kattjevfel Yeah but he asked if it should automatically fallback to 1080p

**Comment by Craig-Macomber** [comment]
> If I had to guess it's probably because discord only supports a list of resolutions. And probably there's a standard for cameras that define what resolutions are supported. But this is only a guess. If someone could test this with a 4k monitor that'd be great.

Same result on 4k. Forcing 1920*1080 fixes it.

**Comment by botiapa** [comment]
@Craig-Macomber Isn't that because without nitro that's the maximum resolution?

**Comment by Craig-Macomber** [comment]
> @Craig-Macomber Isn't that because without nitro that's the maximum resolution?

No idea. Discord doesn't give any errors, it just never loads the camera view. Same problem I've occasionally had with my actual web cam. I also got the same error with some smaller resolutions (ex: 640 by 480). 1920 by 1080 was the only size I found that worked, though I only tried a few.

**Comment by botiapa** [comment]
Thanks for the input.  I'm closing the issue, as the error is on discord's side. Feel free to reopen if you find something interesting.
