### ISSUE TITLE
Adding error logging to exec

### ISSUE THREAD

**Issue by botiapa** [ShayBox/Mon2Cam#39]
We need to pipe the stderr as well when running commands. A possible solution would be to move reading from stdin and stderr into async functions, run them both, and then wait for both to exit (With promises?).

**Comment by ShayBox** [comment]
I agree, Promise.all might be what you're looking for

**Comment by botiapa** [comment]
I'll start working on this right away.

**Comment by ShayBox** [comment]
Yeah console.log restricts length of elements, you'll want to pass it into Deno.inspect first to extend everything to the max length, probably some options you'll have to set to increase object and array lengths too

**Comment by botiapa** [comment]
Done in 87ec754
