### ISSUE TITLE
error in options -hf, --hflip, Horizontally flip the camera

### ISSUE THREAD

**Issue by vifrac** [ShayBox/Mon2Cam#41]
when I use the command "mon2cam -f 30 -d 8 -m 1 -r 640x480 -v" and I use "ffplay /dep/video8" for show output in new window,  I see virtual monitor correctly in that screen. But when I open discord and validate the virtual camera, this monitor show bad horizontally.

then I do try use "mon2cam -f 30 -d 8 -m 1 -r 640x480 -hf -v" but this command showme the help menu, when I validate the file "https://github.com/ShayBox/Mon2Cam/blob/master/src/libraries/options.ts" I can see two lines with the almost same information, that code is correctly ? 

if (typeof p.vflip === "boolean") this.ffmpeg.push(**"-vf vflip")**;
if (typeof p.hflip === "boolean") this.ffmpeg.push(**"-vf hflip"**);

**Comment by ShayBox** [comment]
You likely won't need to flip the image, its mirrored on discord by discord, but yes those two lines are correct and both flags do work together
