### ISSUE TITLE
black screen in discord - using the virtual monitor  

### ISSUE THREAD

**Issue by vifrac** [ShayBox/Mon2Cam#42]
when I use the command  "mon2cam" and select one of the monitors and I use "ffplay /dep/video50" for show output in new window, I see virtual monitor correctly in that screen. But when I open discord and validate the virtual camera, this monitor show black screen, I find a posted in github where speak the problem, I solved change the output resolution with this command  "mon2cam -f 30 -d 8 -m 1 -r 640x480 -v" 

the post: https://github.com/umlaeute/v4l2loopback/issues/274#issuecomment-669653370 

You must validate a resolution aprox  to your monitor because Discord dont accept all resolutions, anybody know other forms I can resolve this issuee?

**Comment by ShayBox** [comment]
Discord doesn't like all resolutions, that's why the scaling flag was added

**Comment by botiapa** [comment]
@ShayBox What do you say about adding warnings when a (probably) unsupported resolution is detected?

**Comment by ShayBox** [comment]
That's fine, non 1080 and 720 resolutions guess?

**Comment by botiapa** [comment]
Yeah that works
