### ISSUE TITLE
Same issue here aswell

### ISSUE THREAD

**Issue by botiapa** [ShayBox/Mon2Cam#5]
Thanks for providing this repo. Unfortunately this code still doesn't work on my 2560\*1080(Ultra widescreen) **nor** on my 1680*1050 display. But it **does** work on my 1920\*1080 monitor. What could be cause of this? Is it because it's a standard in cameras, so discord only supports this resolution?

**Comment by ShayBox** [comment]
Very likely, discord doesn't support non standard resolutions, I encourage anyone to PR a fix, scaling or borders, but I don't know the supported resolutions

**Comment by ShayBox** [comment]
Have you tried #3 / #4 which added scaling?

**Comment by botiapa** [comment]
Yeah this fixed this, but it's obviously not a solution to the problem as it's not scretched.

**Comment by botiapa** [comment]
The weird thing is that on win10 discord correctly displays even a 2560*1080 display. I don't understand why they didn't fix this on the linux version as well.

**Comment by botiapa** [comment]
Okay, so after a bunch of googling, I'm pretty sure I found a solution, by (as you said) adding borders around the stream so it still has a 16:9 aspect ratio. I'll try to PR later, but I don't know one thing about bash scripts, so the code will probably look terrible.

**Comment by botiapa** [comment]
Sent a PR
https://github.com/ShayBox/Mon2Cam/pull/6
