### ISSUE TITLE
PANIC Failed to create V4L2 device with id 50

### ISSUE THREAD

**Issue by frkntlr** [ShayBox/Mon2Cam#50]
I installed it through the aur. It stays that way with or without sudo. When I tried to find a solution I couldn't find a clear solution.

> $ mon2cam -v=log
DEBUG Starting Mon2Cam with the following options: Options {
  framerate: 60,
  device: 50,
  resolution: "",
  ffmpeg: [],
  border: false,
  sound: false,
  wayland: false,
  loggerOptions: { verbose: true, file: "log" },
  execOptions: { verbose: true, output: 3 }
}
DEBUG Checking if V4L2 device exists
DEBUG V4L2 device not found with id 50, creating it

Exec Context: b314c833-3beb-4ab9-8962-8901c522fa7f
    Exec Options:  { verbose: true, output: 3 }
    Exec Command: sudo modprobe -r v4l2loopback
    Exec Command Splits:  [sudo,modprobe,-r,v4l2loopback]
    Exec Result:  { code: 1, success: false },
 output: "modprobe: FATAL: Module v4l2loopback not found."
Exec Context: b314c833-3beb-4ab9-8962-8901c522fa7f

Exec Context: 536892c0-930f-4a7e-8964-3ec540c92594
    Exec Options:  { verbose: true, output: 3 }
    Exec Command: sudo modprobe v4l2loopback video_nr=50 'card_label=Mon2Cam'
    Exec Command Splits:  [sudo,modprobe,v4l2loopback,video_nr=50,'card_label=Mon2Cam']
    Exec Result:  { code: 1, success: false },
 output: "modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/5.8.13-arch1-1"
Exec Context: 536892c0-930f-4a7e-8964-3ec540c92594

DEBUG Exiting
DEBUG V4L2 device created with id 50
PANIC Failed to create V4L2 device with id 50

**Comment by botiapa** [comment]
v4l2loopback is not installed on your system correctly. Please install it first. You can test it with the following command: `sudo modprobe -r v4l2loopback`

**Comment by frkntlr** [comment]
> v4l2loopback is not installed on your system correctly. Please install it first. You can test it with the following command: `sudo modprobe -r v4l2loopback`

>Thanks. The main problem was that linux-headers were not installed.
