### ISSUE TITLE
Documentation notes for Wayland

### ISSUE THREAD

**Issue by PaulDGillis** [ShayBox/Mon2Cam#53]
Just two documentation suggestions to help a few people before reporting an issue.

1. What: mon2cam doesn't work on 1440p monitors with native res and has to be downscaled to 1080p or lower. 
    Why: This is an issue with having v4l2loopback/yuv420p and isn't really noticable when non-discord nitro limits you to streaming 720p anyway. It would probably help people out to know that they have to downscale resolution through mon2cam to make it work on a monitor with higher res than 1080p.

2. What: mon2cam wayland backend should specify that the --resolution downscaling flag doesn't work. 
    Why: A limit in the wf-recorder is there is not currently resolution scaling see https://github.com/ammen99/wf-recorder/issues/77. I'm sure you all knew this as the wayland backend has no flags to specify res, but because of point 1 I think it is important to let people know clearly that the flag doesn't work on wayland.

I do appreciate mon2cam though! Thanks for all the hard work you all do!

**Comment by ShayBox** [comment]
I'll add notices when using flags that don't work on wayland or when selecting a monitor above 1080p

**Comment by ShayBox** [comment]
I added a warning when using wayland about flags, we have a resolution warning for X11 but I can't add it for wayland, wayland support is mostly handled by wf-recorder and since a better tool doesn't exist to my knowledge I don't handle monitor selection in mon2cam for wayland.
