### ISSUE TITLE
Can't execute Argument Error

### ISSUE THREAD

**Issue by roa-sh** [ShayBox/Mon2Cam#58]
I have this issue when i try mon2cam:

error: TS2345 [ERROR]: Argument of type 'undefined' is not assignable to parameter of type 'Sink[] | PromiseLike<Sink[]>'.
			resolve(undefined);
			        ~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/audio.ts:83:12


I have installed all dependencies :(

**Comment by ShayBox** [comment]
Should be fixed now

**Comment by roa-sh** [comment]
Thanks, it is. 

But now i have: 
error: TS2304 [ERROR]: Cannot find name 'reject'.
			reject();
			~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/audio.ts:83:4
