### ISSUE TITLE
cant run the software after install

### ISSUE THREAD

**Issue by alexeyhramov123** [ShayBox/Mon2Cam#61]
DEBUG Starting Mon2Cam with the following options: Options {
  framerate: 60,
  device: 50,
  resolution: "",
  ffmpeg: [],
  border: false,
  sound: false,
  wayland: false,
  loggerOptions: { verbose: true, file: "log" },
  execOptions: { verbose: true, output: 3 }
}
DEBUG Checking if V4L2 device exists
DEBUG V4L2 device not found with id 50, creating it

Exec Context: 2a93d96b-bb11-4a23-8ffc-9e34aa88fea4
    Exec Options:  { verbose: true, output: 3 }
    Exec Command: sudo modprobe -r v4l2loopback
    Exec Command Splits:  [sudo,modprobe,-r,v4l2loopback]
error: Uncaught PermissionDenied: Permission denied (os error 13)
    at processResponse (core.js:226:13)
    at Object.jsonOpSync (core.js:250:12)
    at opRun (deno:cli/rt/40_process.js:19:17)
    at Object.run (deno:cli/rt/40_process.js:103:17)
    at exec (exec.ts:60:15)
    at mod.ts:22:20
    at async mod.ts:15:1

**Comment by sakethkollu** [comment]
Hey, I had the same issue and I resolved it. I am on Ubuntu 20.10

1. Remove your deno installation (assuming you used snap) `sudo snap remove deno`.
2. Download and extract **deno-x86_64-unknown-linux-gnu.zip** from https://github.com/denoland/deno/releases.
3. The extracted file will be named ./deno and I am assuming its in your `~/Downloads/` directory.
4. Ensure ./deno is executable `chmod +x ./deno`
5. Move the file into `/usr/bin/` directory using `sudo mv ./deno /usr/bin/`
6. After "installing" mon2cam you should be able to run `mon2cam` without sudo in terminal and it should no longer have the issue.

**Comment by ShayBox** [comment]
Snaps are always a bad idea, but the only thing you need to do to install deno is  
`curl -fsSL https://deno.land/x/install/install.sh | sh`
