### ISSUE TITLE
After updating sudo, mon2cam no longer works.

### ISSUE THREAD

**Issue by GamerGuy95953** [ShayBox/Mon2Cam#63]
It's me (again). After I updated sudo I restarted my pc and now when I try to type mon2cam in the terminal it requests for the password, after I type it says "sorry, try again." I've tried 5 times and I am 100% sure that is my password. That's how I login in the first place. Is it an issue with sudo or do I need to do something different? Any help would be appreciated. Thanks!

`DEBUG Starting Mon2Cam with the following options: Options {
  framerate: 60,
  device: 50,
  resolution: "",
  ffmpeg: [],
  border: false,
  sound: false,
  wayland: false,
  loggerOptions: { verbose: true },
  execOptions: { verbose: true, output: 3 }
}
DEBUG Checking if V4L2 device exists
DEBUG V4L2 device not found with id 50, creating it

Exec Context: 71ac9c42-952e-4334-982d-044481b3e611
    Exec Options:  { verbose: true, output: 3 }
    Exec Command: sudo modprobe -r v4l2loopback
    Exec Command Splits:  [sudo,modprobe,-r,v4l2loopback]
[sudo] password for user: 
Sorry, try again.
[sudo] password for user: 
Sorry, try again.
[sudo] password for user: 
    Exec Result:  { code: 1, success: false },
 output: "sudo: 3 incorrect password attempts"
Exec Context: 71ac9c42-952e-4334-982d-044481b3e611

Exec Context: e5cad991-9fe3-48cf-b135-0dff2fbd0f48
    Exec Options:  { verbose: true, output: 3 }
    Exec Command: sudo modprobe v4l2loopback video_nr=50 card_label="Mon2Cam"
    Exec Command Splits:  [sudo,modprobe,v4l2loopback,video_nr=50,card_label="Mon2Cam"]
[sudo] password for user: 
Sorry, try again.
[sudo] password for user: 
Sorry, try again.
[sudo] password for user: 
    Exec Result:  { code: 1, success: false },
 output: "sudo: 3 incorrect password attempts"
Exec Context: e5cad991-9fe3-48cf-b135-0dff2fbd0f48

DEBUG Exiting
DEBUG V4L2 device created with id 50
PANIC Failed to create V4L2 device with id 50
[user@UserDesktopLinux ~]$`

**Comment by ShayBox** [comment]
Your password was incorrect, problem with sudo or typing, I've had it happen before, no idea how to fix it, wait a few days and use root to update your system, hopefully sudo works again.

**Comment by GamerGuy95953** [comment]
> Your password was incorrect, problem with sudo or typing, I've had it happen before, no idea how to fix it, wait a few days and use root to update your system, hopefully sudo works again.

I got a fix. Open a blank terminal as root then type your password now you can open a separate terminal and mon2cam works. Wierd. I knew it wasn't a mon2cam thing.

**Comment by GamerGuy95953** [comment]
Now the method I talked about earlier does not work and now I can't even use the terminal as root while still being about to log in to my user account which is an administrator. Nice.

**Comment by ShayBox** [comment]
There's root, and non-root, there's no admins on linux, you have a group that the sudo package looks for to allow you to use it to elevate your command to run as root.  
I would suggest logging into root via su or tty and updating your system, hopefully that fixes your sudo privilege issue.

**Comment by GamerGuy95953** [comment]
> There's root, and non-root, there's no admins on linux, you have a group that the sudo package looks for to allow you to use it to elevate your command to run as root.
> I would suggest logging into root via su or tty and updating your system, hopefully that fixes your sudo privilege issue.

I was able to get it working for a little bit. While it was working I “reset” my password by setting it to my original password and it hasn’t stopped working since. I really do think that when I updated sudo it broke the password system.
