### ISSUE TITLE
No such file or directory (let p = Deno.run({...)

### ISSUE THREAD

**Issue by BenjaminCB** [ShayBox/Mon2Cam#70]
When i try to run the program u just get an error message, that deno can not be found. I have tried different install methods for both mon2cam and deno, but none seem to work.
![bug_report](https://user-images.githubusercontent.com/70470714/112021053-2c6e0c00-8b31-11eb-84de-b2afb31bbb3f.png)

**Comment by ShayBox** [comment]
Do you have sudo and modprobe available as commands?

**Comment by BenjaminCB** [comment]
Had some other problems with v4l2loopback, which needed sorting as well. But changing, to doas instead of sudo on line 22 and 24 in mod.ts, seems to have done the trick. I think adding support for doas, would be a nice addition.
