### ISSUE TITLE
Audio completely unusable, is this on my end?

### ISSUE THREAD

**Issue by Salamidealer** [ShayBox/Mon2Cam#72]
So when I try to screenshare with audio through mon2cam, it does some weird stuff; I can't hear the other person, they can't hear me, but we can both hear whatever audio I am sharing. The other person can hear themselves and they can hear whatever audio I am sharing twice (Echo Cancellation is off). Is this on my end or is there something wrong with the application? 
[Here's the stuff that comes up with -v](https://github.com/ShayBox/Mon2Cam/files/6207454/message.txt)

**Comment by botiapa** [comment]
This might be a dumb question, but did you choose the correct input device in discord? (the mon2cam virtual sink)

**Comment by Salamidealer** [comment]
> This might be a dumb question, but did you choose the correct input device in discord? (the mon2cam virtual sink)

No dumb questions with me, I'm probably the dumb one here :D 
It asks me whether I want to switch audio devices to the mon2cam sink, and I always click yes.

**Comment by botiapa** [comment]
I will look at the logs tomorrow, and see if I find something there. Thanks for the quick response,

**Comment by Salamidealer** [comment]
> I will look at the logs tomorrow, and see if I find something there. Thanks for the quick response,

Thank you :) 
For some reason, it just started working now. I didn't restart my computer nor change anything at all. I have no idea why it works now, but I'm glad it does.

**Comment by botiapa** [comment]
Pulseaudio is a bitch! be sure to reopen, if it breaks again.
