### ISSUE TITLE
error on garuda X64, with zen kernel 5.11.15, nvidia graphics card with the 465.24.02 driver version and gnome 40.

### ISSUE THREAD

**Issue by p3nox** [ShayBox/Mon2Cam#73]
i got the error ¨PANIC Failed to create V4L2 device with id 50¨ when trying to run the mon2cam.
before the update of the graphic driver, (and many other things, it was a full system update, but in 3 days the most important thing that i needed to update was the driver) everything was fine and working, and then i got this error.

**Comment by ShayBox** [comment]
Honestly I'm not using the latest nvidia driver, it's completely broken and causes kernel panics at boot, i'd just downgrade and see if that fixes it

**Comment by p3nox** [comment]
well, as said i`m using garuda (arch based), and i don`t know if i can just downgrade, considering the bleeding edge way of the distro (i`m new at the linux world, so if it has a way, i appreciate if you can please tell me how).

**Comment by ShayBox** [comment]
I use the downgrade package, idk what your repos are like but it'll probably work

**Comment by p3nox** [comment]
in my researches the only way to make it work, is to use the whole old kernel version. this a thing that is very hard considering that some programs just breaks with old kernels on arch.
apparently the only viable way to make it work again on arch linux it´s making a patch. i really like your job, and i really need it, so i`m not happy with the idea of stopping using your program, i would really appreciate your help :)

**Comment by ShayBox** [comment]
Well canary fixed screensharing, and I'm able to use v4l2loopback-dkms with both linux and linux-zen latest, I just can't boot the latest nvidia driver

**Comment by p3nox** [comment]
thanks, the canary fixed the problem :)
