### ISSUE TITLE
error: Uncaught (in promise) PermissionDenied: Permission denied (os error 13) 	let p = Deno.run({ cmd: splits, stdout: out, stderr: out, env: { LANG: "C" } });

### ISSUE THREAD

**Issue by r4msolo** [ShayBox/Mon2Cam#78]
I got this output when trying to run mon2cam, what could it be? I installed all dependencies

>$ mon2cam -v

> WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
> DEBUG Starting Mon2Cam with the following options: Options {
>   hwEncoder: undefined,
>   framerate: 60,
>   device: 50,
>   monitor: undefined,
>   resolution: "",
>   verboseFile: undefined,
>   ffmpeg: [],
>   border: false,
>   sound: false,
>   wayland: false,
>   loggerOptions: { verbose: true },
>   execOptions: { verbose: true, output: 3 }
> }
> DEBUG Checking if V4L2 device exists
> DEBUG V4L2 device not found with id 50, creating it
> 
> Exec Context: 64d230c6-55dd-479a-90e3-b6a0e898566a
>     Exec Options:  { verbose: true, output: 3 }
>     Exec Command: sudo modprobe -r v4l2loopback
>     Exec Command Splits:  [sudo,modprobe,-r,v4l2loopback]
> error: Uncaught (in promise) PermissionDenied: Permission denied (os error 13)
> 	let p = Deno.run({ cmd: splits, stdout: out, stderr: out, env: { LANG: "C" } });
> 	             ^
>     at unwrapOpResult (deno:core/core.js:99:13)
>     at Object.opSync (deno:core/core.js:113:12)
>     at opRun (deno:runtime/js/40_process.js:20:17)
>     at Object.run (deno:runtime/js/40_process.js:104:17)
>     at exec (https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/libraries/exec.ts:61:15)
>     at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/mod.ts:22:20
>     at async https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/mod.ts:15:1

**Comment by ShayBox** [comment]
Don't install deno with snap
