### ISSUE TITLE
When starting Mon2Cam on Manjaro, I get this error.

### ISSUE THREAD

**Issue by BlueCyro** [ShayBox/Mon2Cam#9]
`modprobe: Error: could not insert 'v4l2loopback': Bad address.`

Here are my neofetch stats: https://i.imgur.com/ylTj3CK.png

I've installed it via AUR so all of the dependencies are satisfied.
This would be very beneficial as I've recently switched to linux and this has been bugging me for a little while now.

**Comment by ShayBox** [comment]
Only 3 gpus? Come on man
It seems to be a kernel/v4l2loopback problem, I have a feeling it's because you're using a bleeding edge kernel, try normal which should be 5.3.7, if that doesn't fix it try the dkms-git package, if that doesn't work I'll need logs from dmesg 'dmesg -wH' for live output

**Comment by BlueCyro** [comment]
After switching to 5.3.7 for the kernel, the program starts and gives me an option to switch between whichever monitor, but the Mon2Cam interface just presents either a black screen or a loading screen when activating the camera option, this happens with both the v4l2loopback-dkms and dkms-git versions. P.S. Yes, 3 GPUs is rather nice, though I can only use two monitors since nvidia's drivers suck on linux super duper badly.

**Comment by ShayBox** [comment]
Yeah, I feel that, for some reason nvidia cant get dual nvidia gpu working, nvidia + (amd/intel) works perfect with prime, but not dual nvidia :anger: 
That sounds like a common problem, weird resolution/aspect ratio monitor, try the scaling/border options, discord doesn't like weird things

**Comment by BlueCyro** [comment]
Got it working! Set the resolution to 1920x1080 for the scaling options and it works perfectly now. Thank you kindly for making this tool, it's a wonder why the discord team hasn't fixed this yet. Specifically adding the `-r 1920:1080` switch for the potential future people reading this.

(Unrelated to the Mon2Cam problem)
P.S. The specific problem I'm having with my GPU setup is that no monitor connected to the iGPU is detected, and I can't seem to enable a secondary X screen for my other two connected to my 970, so I'm gonna have to give up one monitor while the two DisplayPort to DVI cables I ordered make their way to me tomorrow as of the time of writing this. You have to have all of your monitors plugged into one card if you want more monitors evidently, and X only supports four per card from what I hear, so no more 5 monitor setup for me. :(

**Comment by ShayBox** [comment]
I'm not sure about 4 monitors per screen, but you don't want multiple X screens, each screen is a seperate X instance, no window sharing, mouse movement between, etc, nvidia tried to fix that with xinerama years ago but it wasnt very well supported, if you have nvidia and intel/amd you can get your amd/intel gpu to use prime on your nvidia's gpu X screen, it seems to just work out of the box for me, though you may need intel drivers, I used amd to do it

**Comment by BlueCyro** [comment]
Yeah Xinerama just doesn't work, lol. Oh well though, I'll be getting my cables later today so the problem should be mostly nonexistant. *Hopefully.*

**Comment by ShayBox** [comment]
I had problems with cables, my two secondary monitors are analog and I have a newer gpu that only outputs digital, so I had to buy adapters but passive adapters don't work/exist, you have to have an active adapter with electronics inside, basically mimics a monitor so both my adapters always show 1080p as native, when my monitors max at 1366x768, the edid values don't get through.
